# Generated by Django 4.0.6 on 2022-07-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Closeprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valordefecho', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('exchange', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=255)),
                ('precomax', models.FloatField()),
                ('precomin', models.FloatField()),
                ('closeprice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.closeprice')),
            ],
        ),
    ]
