# Generated by Django 4.0.6 on 2022-07-20 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='closeprice',
        ),
    ]
