# Generated by Django 4.0.6 on 2022-07-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_stock_closeprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='lastprice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
