# Generated by Django 4.0.6 on 2022-07-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_stock_lastprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='lastprice',
            field=models.FloatField(null=True),
        ),
    ]
