# Generated by Django 4.0.6 on 2022-07-22 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_stock_lastprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='exchange',
            new_name='frequencia',
        ),
    ]
