# Generated by Django 4.0.6 on 2022-07-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_stock_frequencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=255, null='1m'),
        ),
    ]
